baseURL = "/"
languageCode = "en-us"
title = "GEOVID"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Covid-19"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Proposal"
    url = "/Proposal/"
    weight = 2
[[menu.main]]
    name = "Poster"
    url = "/poster/"
    weight = 3
[[menu.main]]
    name = "Application"
    url = "/application/"
    weight = 4
[[menu.main]]
    name = "Research Paper"
    url = "/reserach-paper/"
    weight = 5
    

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  
  homepage_image = '/images/logo2.jpg'
  homepage_intro = ''

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = trueWS

  [params.homepage_meta_tags]
    meta_description = ""
    meta_og_title = "Geovid"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo2.jpg"
      standard  = "/images/logo2.jpg"
  
[build]
  publish = "Blogdown/public"
  command = "cd exampleSite && hugo --gc --themesDir ../.."

[build.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

